### ISSUE TITLE
Clean Highline values before setting

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cyoi#1]
Raised at https://github.com/StarkAndWayne/bosh-bootstrap/issues/194

``` yaml

---
bosh:
  name: firstbosh
provider:
  name: openstack
  credentials:
    openstack_username: !str:HighLine::String test
    openstack_api_key: !str:HighLine::String test
    openstack_tenant: !str:HighLine::String test
    openstack_auth_url: !str:HighLine::String http://myurl.com/v2.0/tokens
  region: !str:HighLine::String
```
